spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/captain;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50

  mail:
    host: smtp.gmail.com
    port: 587
    username: modunaeggu@gmail.com
    password: jsxtgzwirzbvctix
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true

loggin.lvel:
  root: info
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  #org.hibernate.type: trace

app.host: http://localhost:8080